// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBudgODfdJWwj7r64txONVJO4F_KFV1Wxk',
    appId: '1:926223610539:web:eba719744edde9c3d5bdee',
    messagingSenderId: '926223610539',
    projectId: 'krokapp-8aa94',
    authDomain: 'krokapp-8aa94.firebaseapp.com',
    storageBucket: 'krokapp-8aa94.appspot.com',
    measurementId: 'G-055TR22G5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxA85zQgl3ROlxcOfVOq6QSrVMwOPRTw8',
    appId: '1:926223610539:android:f3af137e13bde888d5bdee',
    messagingSenderId: '926223610539',
    projectId: 'krokapp-8aa94',
    storageBucket: 'krokapp-8aa94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbuCfVUGbwzX_SEqieYd0rgUVDQkwd_ko',
    appId: '1:926223610539:ios:53b5bef9442433e2d5bdee',
    messagingSenderId: '926223610539',
    projectId: 'krokapp-8aa94',
    storageBucket: 'krokapp-8aa94.appspot.com',
    iosBundleId: 'com.example.krokApp',
  );
}
